default:
  readTimeout: 60000
  connectTimeout: 60000

spring:
  rest:
    connection:
      connection-request-timeout: ${default.connectTimeout}
      connect-timeout: ${default.connectTimeout}
      read-timeout: ${default.readTimeout}
  datasource:
    jdbc-url: jdbc:mysql://192.168.1.12:3306/foundation?autoReconnect=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: "service"
    password: "!Service123"
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: hikariCP1
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  transaction: #transaction
    default-timeout: 10
    rollback-on-commit-failure: true
  redis:
    host: 192.168.1.12
    port: 6379
    pool:
      max-idle: 100 # 连接池中的最大空闲连接
      min-idle: 10 # 连接池中的最小空闲连接
      max-active: 1000 #连接池最大连接数（使用负值表示没有限制）
      max-wait: 5000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 2000 # 连接超时时间（毫秒）
      #sentinel:
      #master: # name of Redis server
      #nodes: # comma-separated list of host:port pairs
rocketmq:
  name-server: 192.168.1.12:9876
  producer:
    group: notify_producer_group

mq-topic:
  result-noitfy-r0: result-notify
  result-notify-r1: result-notify-r1
  result-notify-r2: result-notify-r2
  result-notify-r3: result-notify-r3
  intervals: #通知时间间隔s
    r0-r1: 18
    r1-r2: 180
    r2-r3: 1800


logging:
  level:
    root: info
    com:
      shuyuan:
        judd:
          notify:
            listener: debug